# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.
- id: ceph_test-deployment-puppet
  type: puppet
  role: [ceph-osd]
  required_for: [netconfig]
#  requires: [globals]
  parameters:
    puppet_manifest: ceph_test.pp
    puppet_modules: /etc/puppet/modules
    timeout: 600
